apiVersion: v1
data:
  azurestorageaccountkey: {{ b64enc .Values.azurefile.storage.key }}
  azurestorageaccountname: {{ b64enc .Values.azurefile.storage.accountname }}
kind: Secret
metadata:
  name: {{ .Values.azurefile.storage.sharename }}-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque