apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.azuredisk.storage.diskname }}
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: {{ .Values.azuredisk.storage.quota }}