apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.azurefile.storage.sharename }}
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.azurefile.storage.quota }}