apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.azurefile.storage.sharename }}
spec:
  capacity:
    storage: {{ .Values.azurefile.storage.quota }}
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
     namespace: {{ .Values.global.namespace }}
     name: {{ .Values.azurefile.storage.sharename }}
  azureFile:
    secretName: {{ .Values.azurefile.storage.sharename }}-secret
    secretNamespace: {{ .Values.global.namespace }}
    shareName: {{ .Values.azurefile.storage.sharename }}
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl